# Site settings


title: kai matheson

email: ramatheson@vassar.edu

description: > # this means to ignore newlines until "baseurl:"

  aspiring quantitative urbanist/computational social scientist

baseurl:  # the subpath of your site, e.g. /blog/


url:  # the base hostname & protocol for your site


twitter_username: mathematikai

github_username:  kaimath



# Build settings


markdown: kramdown





highlighter: rouge




# Pagination


paginate: 15


paginate_path: "/blog/page:num/"






collections:
  

portfolio:
    

output: true
    

permalink: /portfolio/:path/
  