# Site settings

title: kai matheson

email: ramatheson@vassar.edu

description: aspiring quantitative urbanist/computational social scientist
baseurl:  /home
url:
twitter_username: mathematikai
github_username:  kaimath

# Build settings

markdown: kramdown


highlighter: rouge


# Pagination

paginate: 15

paginate_path: "/blog/page:num/"



collections:
  
portfolio:
    
output: true
    
permalink: /portfolio/:path/
  
poetry:
    output: true
    
permalink: /poetry/:path/


